apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-alex-service
spec:
  type: NodePort
  selector:
    app: tech-challenge-alex-api-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000